<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Granit.Notifications.Sms\Granit.Notifications.Sms.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Granit.Notifications.Sms.Sns.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
