<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Granit.Diagnostics</PackageId>
    <Description>Kubernetes health check infrastructure for Granit applications. Exposes liveness, readiness and startup probes with anti-stampede cache and structured JSON format.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Granit.Diagnostics.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Granit.Timing\Granit.Timing.csproj" />
  </ItemGroup>

</Project>
