using Cronos;
using Granit.Timing;
using Microsoft.Extensions.Logging;
using Wolverine;
using Wolverine.Runtime.Agents;

namespace Granit.BackgroundJobs.Internal;

/// <summary>
/// Wolverine singleton agent that initializes recurring job scheduling on cluster startup.
/// </summary>
/// <remarks>
/// <para>
/// URI: <c>granit-background-jobs://singleton</c> (generated by <see cref="SingularAgent"/>).
/// Wolverine guarantees that exactly one node in the cluster runs this agent at a time,
/// preventing duplicate scheduling on multi-node startup.
/// </para>
/// <para>
/// <b>Anti-doublon guarantee:</b> before scheduling a job, <see cref="startAsync"/> checks
/// whether <see cref="BackgroundJobDefinition.NextExecutionAt"/> is already in the future.
/// If it is, the job is already scheduled via the Outbox — no message is published.
/// </para>
/// <para>
/// Registered via <c>services.AddSingularAgent&lt;CronSchedulerAgent&gt;()</c> in
/// <c>AddGranitBackgroundJobs()</c>.
/// </para>
/// </remarks>
internal sealed partial class CronSchedulerAgent(
    IBackgroundJobStore store,
    IMessageBus bus,
    IClock clock,
    ILogger<CronSchedulerAgent> logger) : SingularAgent("granit-background-jobs")
{
    /// <inheritdoc/>
    protected override async Task startAsync(CancellationToken cancellationToken)
    {
        IReadOnlyList<BackgroundJobDefinition> jobs = await store.GetEnabledJobsAsync(cancellationToken).ConfigureAwait(false);

        foreach (BackgroundJobDefinition job in jobs)
        {
            if (job.NextExecutionAt.HasValue && job.NextExecutionAt.Value > clock.Now)
            {
                LogJobAlreadyScheduled(logger, job.JobName, job.NextExecutionAt.Value);
                continue;
            }

            DateTimeOffset? next = ComputeNext(job.CronExpression);
            if (next is null)
            {
                LogJobCronInvalid(logger, job.JobName, job.CronExpression);
                continue;
            }

            object message = CreateMessage(job.MessageType, job.JobName);
            await bus.ScheduleAsync(message, next.Value).ConfigureAwait(false);
            await store.RecordNextExecutionAsync(job.JobName, next.Value, cancellationToken).ConfigureAwait(false);
            LogJobScheduled(logger, job.JobName, next.Value);
        }
    }

    /// <inheritdoc/>
    protected override Task stopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    private DateTimeOffset? ComputeNext(string cronExpression)
    {
        try
        {
            CronExpression cron;
            try
            {
                cron = CronExpression.Parse(cronExpression, CronFormat.IncludeSeconds);
            }
            catch (CronFormatException)
            {
                cron = CronExpression.Parse(cronExpression);
            }

            return cron.GetNextOccurrence(clock.Now, TimeZoneInfo.Utc);
        }
        catch (CronFormatException)
        {
            return null;
        }
    }

    internal static object CreateMessage(string messageType, string jobName)
    {
        Type? type = Type.GetType(messageType);
        if (type is null)
        {
            throw new InvalidOperationException(
                $"Cannot resolve message type '{messageType}' for job '{jobName}'. " +
                "Ensure the assembly containing the message is loaded.");
        }

        return Activator.CreateInstance(type)
            ?? throw new InvalidOperationException(
                $"Cannot instantiate message type '{type.Name}' for job '{jobName}'.");
    }

    [LoggerMessage(Level = LogLevel.Debug,
        Message = "BackgroundJob '{JobName}' already scheduled for {Next} — skipping.")]
    private static partial void LogJobAlreadyScheduled(
        ILogger logger, string jobName, DateTimeOffset next);

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "BackgroundJob '{JobName}' has invalid cron '{Cron}' — cannot schedule.")]
    private static partial void LogJobCronInvalid(
        ILogger logger, string jobName, string cron);

    [LoggerMessage(Level = LogLevel.Information,
        Message = "BackgroundJob '{JobName}' scheduled for first occurrence at {Next}.")]
    private static partial void LogJobScheduled(
        ILogger logger, string jobName, DateTimeOffset next);
}
