<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Granit.Notifications.Sms.AwsSns</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Granit.Notifications.Sms\Granit.Notifications.Sms.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Granit.Notifications.Sms.AwsSns.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
