<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Granit.Notifications.MobilePush\Granit.Notifications.MobilePush.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Granit.Notifications.MobilePush.Sns.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
