<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Granit.Security</PackageId>
    <Description>Abstractions de sécurité pour les applications .NET Digital Dynamics : ICurrentUserService.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Granit.Core\Granit.Core.csproj" />
  </ItemGroup>

</Project>
