namespace Granit.Notifications;

/// <summary>
/// Notification data auto-generated by the entity tracking interceptor
/// when a tracked property changes on an <see cref="ITrackedEntity"/>.
/// </summary>
public sealed record EntityStateChangedData
{
    public required string EntityType { get; init; }
    public required string EntityId { get; init; }
    public required string PropertyName { get; init; }
    public string? OldValue { get; init; }
    public string? NewValue { get; init; }
    public required DateTimeOffset ChangedAt { get; init; }
    public string? ChangedByUserId { get; init; }
}
